version: "2"
services:
  spring-boot-redisson:
    build: spring-boot-redisson
    container_name: 'spring-boot-redisson'
    environment:
      - spring_profiles_active=docker
      - REDIS_HOST=redis
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - redis-network
  redis:
    image: "redis:alpine"
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - redis-network
networks:
  redis-network: